name: sputnik_cardio_backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  shelf: 1.4.2
  shelf_router: 1.1.4
  shelf_cors_headers: 0.1.5



dev_dependencies:
  lints: 6.0.0
  test: 1.26.3
